apiVersion: v1
kind: ServiceAccount
metadata:
  name: gke-demo-sa
  namespace: gke-demo
  annotations:
    # This links the Kubernetes SA to the GCP service account (Workload Identity)
    iam.gke.io/gcp-service-account: GCP_SERVICE_ACCOUNT_EMAIL_PLACEHOLDER
