apiVersion: v1
kind: ServiceAccount
metadata:
  name: gke-demo-sa
  namespace: gke-demo
  annotations:
    # This links the Kubernetes SA to the GCP service account (Workload Identity)
    iam.gke.io/gcp-service-account: github-gke-deployer@project-daa5fabb-04a9-49a3-945.iam.gserviceaccount.com
