apiVersion: v1
kind: Service
metadata:
  name: gke-demo-svc
  namespace: gke-demo
spec:
  type: LoadBalancer
  selector:
    app: gke-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
