apiVersion: v1
kind: ServiceAccount
metadata:
  name: gke-demo-sa
  namespace: gke-demo
  annotations:
    # Runtime GCP service account used by pods via Workload Identity.
    iam.gke.io/gcp-service-account: gke-demo-sa@project-daa5fabb-04a9-49a3-945.iam.gserviceaccount.com
